import DocFooter from "@/app/components/DocFooter";

export default function TermsOfService() {
  return (
    <article className="content-doc">
      <span className="doc-kicker"><span className="pip" />Legal · Terms</span>
      <h1 className="doc-title">Terms of Service</h1>
      <p className="doc-meta">Last updated: {new Date().toLocaleDateString()}</p>

      <h2>General Terms</h2>
      <p>
        By accessing AIWerewolf.net, you agree to these Terms of Service. While we strive to provide a
        consistent experience, the site is provided &quot;as is&quot; and we make no guarantees about service
        availability.
      </p>

      <h2>Usage Restrictions</h2>
      <p>When using this site, you agree to:</p>
      <ul className="doc-list">
        <li>Respect other players and AI agents.</li>
        <li>Avoid using offensive or inappropriate language in game chat.</li>
        <li>Not attempt to disrupt the service, exploit game mechanics, or scrape game data without
          permission.</li>
      </ul>

      <h2>No Responsibility for AI Content</h2>
      <p>
        This game uses AI models (such as GPT, Claude, and Gemini) to generate character dialogue and
        decisions. While we implement filters, we are not responsible for the unpredictable or incorrect
        content generated by these third-party AI systems.
      </p>

      <h2>Modification of Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Changes will be reflected here with a new
        &quot;Last Updated&quot; date.
      </p>

      <DocFooter />
    </article>
  );
}
