import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="page-section narrow" style={{ color: 'var(--ember-ink-0)' }}>
      <h1 className="h-title">Terms of Service</h1>
      <p className="console-text" style={{ fontSize: 14, color: 'var(--ember-ink-3)', marginBottom: 24 }}>
        Last updated: {new Date().toLocaleDateString()}
      </p>

      <Section title="GENERAL TERMS">
        <p>
          By accessing AIWerewolf.net, you agree to these Terms of Service. The site is provided &quot;as is&quot;
          and we make no guarantees about service availability.
        </p>
      </Section>

      <Section title="USAGE RESTRICTIONS">
        <p>When using this site, you agree to:</p>
        <ul style={{ listStyleType: 'disc', paddingLeft: 24 }}>
          <li>Respect other players and AI agents.</li>
          <li>Avoid offensive or inappropriate language in game chat.</li>
          <li>Not attempt to disrupt the service, exploit game mechanics, or scrape data.</li>
        </ul>
      </Section>

      <Section title="AI CONTENT">
        <p>
          This game uses AI models to generate character dialogue and decisions.
          While we implement filters, we are not responsible for unpredictable content generated by
          third-party AI systems.
        </p>
      </Section>

      <Section title="MODIFICATION">
        <p>
          We reserve the right to modify these terms at any time. Changes will be reflected here with a new &quot;Last Updated&quot; date.
        </p>
      </Section>

      <div className="hr-pixel" />
      <Link href="/" className="pixel-text" style={{ fontSize: 9, color: 'var(--ember-ink-3)', textDecoration: 'none' }}>
        ← BACK TO HOME
      </Link>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <div className="h-eyebrow">{title}</div>
      <div className="hr-pixel" style={{ marginTop: 4, marginBottom: 12 }} />
      <div style={{ fontSize: 15, color: 'var(--ember-ink-1)', lineHeight: 1.7, display: 'flex', flexDirection: 'column', gap: 8 }}>
        {children}
      </div>
    </section>
  );
}
