import type {Metadata} from "next";
import DocFooter from "@/app/components/DocFooter";
import {CONTACT_EMAIL} from "@/app/config/external-links";

export const metadata: Metadata = {
    title: "Terms of Service — Werewolf AI",
    description: "Terms for using AIWerewolf.net.",
    alternates: { canonical: "/terms" },
};

export default function TermsOfService() {
  return (
    <article className="content-doc">
      <span className="doc-kicker"><span className="pip" />Legal · Terms</span>
      <h1 className="doc-title">Terms of Service</h1>
      <p className="doc-meta">Last updated: {new Date().toLocaleDateString()}</p>

      <h2>General Terms</h2>
      <p>
        By accessing AIWerewolf.net, you agree to these Terms of Service. While we strive to provide a
        consistent experience, the site is provided &quot;as is&quot; and we make no guarantees about service
        availability.
      </p>

      <h2>Usage Restrictions</h2>
      <p>When using this site, you agree to:</p>
      <ul className="doc-list">
        <li>Respect other players and AI agents.</li>
        <li>Avoid using offensive or inappropriate language in game chat.</li>
        <li>Not attempt to disrupt the service, exploit game mechanics, or scrape game data without
          permission.</li>
      </ul>

      <h2>AI-Generated Content</h2>
      <p>
        Everything you see in a game — character names, backstories, dialogue, story text, portraits and
        voices — is generated at the moment you play it by third-party AI models from the providers listed
        on our <a href="/about">About</a> page. Nothing is drawn from a library of pre-made assets.
      </p>
      <p>
        We do not host, distribute, or knowingly incorporate third-party copyrighted works, characters, or
        trademarks. What we provide is access to the AI models; the content itself is produced by those
        models in response to the theme and instructions a player supplies.
      </p>

      <h2>No Responsibility for AI Content</h2>
      <p>
        While we implement filters, we are not responsible for the unpredictable or incorrect content
        generated by these third-party AI systems.
      </p>

      <h2>Your Responsibility</h2>
      <p>
        Game themes and instructions for the Game Master are written by you. You agree not to enter prompts
        intended to reproduce copyrighted characters, trademarks, or identifiable real people. Content
        generated from your prompts is your responsibility, and we may remove games or generated content
        that breaches this.
      </p>

      <h2>Ownership of Generated Content</h2>
      <p>
        We claim no ownership of the text, images or audio generated during your games — use them as you
        like. We make no warranty that any generated output is free of third-party rights, and you use it
        at your own risk. Your use of the underlying models also remains subject to each provider&apos;s own
        terms.
      </p>

      <h2>Reporting a Concern</h2>
      <p>
        If you believe content generated or displayed here infringes your rights, email{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> with a description of the work and a link to
        where it appears. We will review and remove infringing content promptly.
      </p>

      <h2>Modification of Terms</h2>
      <p>
        We reserve the right to modify these terms at any time. Changes will be reflected here with a new
        &quot;Last Updated&quot; date.
      </p>

      <DocFooter />
    </article>
  );
}
